config/routes.rb
Saygepoints::Application.routes.draw do
  devise_for :users

  root :to => "points#index"
  
  resources :points
  resources :point_types
  resources :sayges, :only => [:index, :show]
  

end

app/models/point_balance.rb
class PointBalance < ActiveRecord::Base
  belongs_to :point_type
  belongs_to :user
end
# == Schema Information
#
# Table name: point_balances
#
#  id            :integer         not null, primary key
#  amount        :integer
#  user_id       :integer
#  point_type_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#

app/models/point_delta.rb
class PointDelta < ActiveRecord::Base
  belongs_to :from_user, :class_name => 'User'
  belongs_to :to_user, :class_name => 'User'
  belongs_to :point_type
  
  after_create :add_to_balance
  
  def add_to_balance
    balance = PointBalance.where(:user_id => self.to_user.id,
      :point_type_id => self.point_type.id)
    if balance.empty?
      balance = PointBalance.create(:user_id => self.to_user.id,
        :point_type_id => self.point_type.id)
    else
      balance = balance.first
    end
    
    balance.amount += self.amount
    balance.save
  end
end
# == Schema Information
#
# Table name: point_deltas
#
#  id            :integer         not null, primary key
#  amount        :integer
#  reason        :text
#  from_user_id  :integer
#  to_user_id    :integer
#  created_at    :datetime
#  updated_at    :datetime
#  point_type_id :integer
#

app/models/point_type.rb
class PointType < ActiveRecord::Base
  has_many :point_deltas
  has_many :point_balances
end
# == Schema Information
#
# Table name: point_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation,
    :remember_me
  
  has_many :points_given, :class_name => 'PointDelta',
    :inverse_of => :from_user
  has_many :points_received, :class_name => 'PointDelta',
    :inverse_of => :to_user
  has_many :point_balances
end
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/point_types_controller.rb
class PointTypesController < ApplicationController
  def index
    respond_to do |format|
      format.json { render :json => PointType.all.map(&:name).to_json }
    end
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @point_deltas = PointDelta.all
  end
  
  def new
    @point_delta = PointDelta.new
  end
  
  def create
    @delta = params[:point_delta]
    @point_delta = PointDelta.new(:amount => @delta[:amount],
      :reason => @delta[:reason])
    @from_user = current_user
    @to_user = User.find_by_name(params['to_user'])

    @point_type = PointType.find_by_name(params['point_type'])
    if @point_type.nil?
      @point_type = PointType.create(:name => params['point_type'])
    end
    
    if @from_user == @to_user
      redirect_to :back, :flash => { :error =>
        "You can't give yourself points. Nice try, though."
      }
    else
      @point_delta.from_user = @from_user
      @point_delta.to_user = @to_user
      @point_delta.point_type = @point_type
      if @point_delta.save
        @verb = ((@delta[:amount].to_i < 0) ? 'taken' : 'given')
        redirect_to root_path, :flash => { :success => "Points #{@verb}."}
      else
        render 'new'
      end
    end
  end
end

app/controllers/sayges_controller.rb
class SaygesController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render :json => User.all.map(&:name).to_json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/point_types_helper.rb
module PointTypesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/sayges_helper.rb
module SaygesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Saygepoints</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <h1>SaygePoints</h1>
  
  <nav id="sections">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Sayges", sayges_path %></li>
    </ul>
  </nav>
  
  <% flash.each do |key, val| %>
    <p class="flash <%= key %>"><%= val %></p>
  <% end %>
  
  <%= yield %>
</body>
</html>

app/views/points/_point_delta.html.erb
<div class="points">
  <%= point_delta.from_user.name %> gave <%= point_delta.to_user.name %>
  <%= point_delta.amount %> <%= point_delta.point_type.name %> points for
  <%= point_delta.reason %>
</div>

app/views/points/index.html.erb
<%= link_to "Give/Take Points", new_point_path %>
<div id="points-list">
  <% if @point_deltas.any? %>
    <% @point_deltas.each do |delta| %>
      <%= render 'points/point_delta', :point_delta => delta %>
    <% end %>
  <% else %>
    <p class="info">No one has any points yet.</p>
  <% end %>
</div>

app/views/points/new.html.erb
<%= javascript_include_tag "autocomplete_point_fields" %>

<%= form_for(@point_delta, :url => points_path) do |f| %>
  <%= f.number_field :amount %>
  <%= text_field_tag "point_type" %> Points to
  <%= text_field_tag "to_user" %> for
  <%= f.text_field :reason %>
  
  <%= f.submit "Thus sayeth the sayge!" %>
<% end %>

app/views/sayges/index.html.erb
<div class="sayges">
  <% User.all.each do |user| %>
    <div class="sayge">
      <p><%= user.name %>
      <% if user.point_balances.any? %>
        has</p>
        <ul>
          <% user.point_balances.each do |point_balance| %>
            <li><%= point_balance.amount %>
             <%= point_balance.point_type.name %> Points</li>
          <% end %>
        </ul>
      <% else %>
        doesn't have any points yet.
      <% end %>
    </div>
  <% end %>
</div>